name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Set executable permissions for Selenium Manager
      run: chmod +x /home/runner/work/Selenium-Web-Driver/Selenium-Web-Driver/TestProject1/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
    - name: Set executable permissions for Selenium Manager
      run: chmod +x /home/runner/work/Selenium-Web-Driver/Selenium-Web-Driver/TestProject2/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
    - name: Set executable permissions for Selenium Manager
      run: chmod +x /home/runner/work/Selenium-Web-Driver/Selenium-Web-Driver/TestProject3/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
    - name: Run tests
      run: dotnet test --filter TestCategory=ChromeTests
